# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sorry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorry',
            name='relationship',
            field=models.CharField(choices=[('Lover', 'Lover'), ('Ex-Lover', 'Ex-Lover'), ('Family', 'Family'), ('Friend', 'Friend'), ('Enemy', 'Enemy'), ('Co-Worker', 'Co-Worker'), ('Stranger', 'Stranger')], default=django.utils.timezone.now, max_length=17),
            preserve_default=False,
        ),
    ]
