# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sorry', '0002_sorry_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sorry',
            name='published_date',
        ),
        migrations.AddField(
            model_name='sorry',
            name='relationship',
            field=models.CharField(choices=[('FAM', 'Family'), ('SOT', 'Significant Other'), ('EXL', 'EX-Lover'), ('FRI', 'Friend'), ('COW', 'Co-Worker'), ('STG', 'Stranger')], default=django.utils.timezone.now, max_length=3),
            preserve_default=False,
        ),
    ]
